#!/usr/bin/env bash

auth_token_decoded=$(echo "$COMPLICE_AUTH_TOKEN" | base64 -d)

auth_token_param="auth_token=$auth_token_decoded"

url=https://complice.co/api/v0/u/me/today/timer
state=$(curl -s "$url/all?$auth_token_param" | jq .ticker.state)

echo "Current pomodoro state: $state"

if [ "$state" == '"inactive"' ]; then
    echo "Starting pomodoro timer"
    curl -s -X POST "$url/startpomodoro?$auth_token_param" > /dev/null
else
    echo "Canceling pomodoro timer"
    curl -s -X POST "$url/cancel?$auth_token_param" > /dev/null
fi
