{
  agenix,
  all-overlays,
  home,
  fix-nixpkgs-path,
  rev,
  nixosModules,
}:
{
  system = "aarch64-linux";
  modules = [
    (
      { ... }:
      {
        nixpkgs.overlays = all-overlays;
      }
    )
    fix-nixpkgs-path
    home.nixosModules.home-manager
    # My settings for orb
    (
      { pkgs, ... }:
      {
        nix = {
          package = pkgs.nixVersions.stable;

          extraOptions = ''
            filter-syscalls = false
            experimental-features = nix-command flakes
            extra-platforms = aarch64-linux
          '';
          settings.trusted-users = [ "@wheel" ];
          # trusted-substituters = [
          #   "https://nix-community.cachix.org"
          #   "https://anmonteiro.cachix.org"
          # ];
          # trusted-public-keys = [
          #   "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
          #   "anmonteiro.cachix.org-1:KF3QRoMrdmPVIol+I2FGDcv7M7yUajp4F2lt0567VA4="
          # ];
        };
        programs.zsh.enable = true;
        programs.git.lfs.enable = true;
        programs.nix-ld.enable = true;
        programs.nix-ld.libraries = with pkgs; [
          # Add any missing dynamic libraries for unpackaged programs
          # here, NOT in environment.systemPackages
        ];

        environment.systemPackages = with pkgs; [
          vim
          git
        ];
        home-manager.useGlobalPkgs = true;
        home-manager.useUserPackages = true;
        home-manager.users.d4hines =
          { ... }:
          {
            imports = [
              (
                { ... }:
                {
                  home.stateVersion = "24.05";
                }
              )
              nixosModules.home
            ];
          };
      }
    )
    # Orbs original settings
    (
      {
        config,
        pkgs,
        modulesPath,
        ...
      }:
      {
        imports = [
          # Include the default lxd configuration.
          "${modulesPath}/virtualisation/lxc-container.nix"
          # Include the container-specific autogenerated configuration.
          ./lxd.nix
          # Include the OrbStack-specific configuration.
          ./orbstack.nix
        ];

        users.users.d4hines = {
          uid = 501;
          extraGroups = [ "wheel" ];
          shell = pkgs.zsh;

          # simulate isNormalUser, but with an arbitrary UID
          isSystemUser = true;
          group = "users";
          createHome = true;
          home = "/home/d4hines";
          homeMode = "700";
          useDefaultShell = true;
        };

        security.sudo.wheelNeedsPassword = false;

        # This being `true` leads to a few nasty bugs, change at your own risk!
        users.mutableUsers = false;

        time.timeZone = "America/New_York";

        networking = {
          dhcpcd.enable = false;
          useDHCP = false;
          useHostResolvConf = false;
        };

        systemd.network = {
          enable = true;
          networks."50-eth0" = {
            matchConfig.Name = "eth0";
            networkConfig = {
              DHCP = "ipv4";
              IPv6AcceptRA = true;
            };
            linkConfig.RequiredForOnline = "routable";
          };
        };

        # This option defines the first version of NixOS you have installed on this particular machine,
        # and is used to maintain compatibility with application data (e.g. databases) created on older NixOS versions.
        #
        # Most users should NEVER change this value after the initial install, for any reason,
        # even if you've upgraded your system to a new NixOS release.
        #
        # This value does NOT affect the Nixpkgs version your packages and OS are pulled from,
        # so changing it will NOT upgrade your system - see https://nixos.org/manual/nixos/stable/#sec-upgrading for how
        # to actually do that.
        #
        # This value being lower than the current NixOS release does NOT mean your system is
        # out of date, out of support, or vulnerable.
        #
        # Do NOT change this value unless you have manually inspected all the changes it would make to your configuration,
        # and migrated your data accordingly.
        #
        # For more information, see `man configuration.nix` or https://nixos.org/manual/nixos/stable/options#opt-system.stateVersion .
        system.stateVersion = "24.05"; # Did you read the comment?
      }
    )
  ];
}
