theme = "catppuccin_frappe"

[editor]
auto-save = true

[editor.file-picker]
hidden = false

[keys.normal]
C-r = ":reload-all"

"C-S-F" = ":reload-all"

"C-y" = ":config-reload"

"space" = { w = { d = "wclose"}}

C-7 = "toggle_comments"

