#!/usr/bin/env node
const path = require("path");
const { execSync } = require("child_process");
const { find_git_root, updateWorkspaceFile } = require("./helpers");

const branchName = process.argv[2];
const root = find_git_root(process.cwd());
const fullPath = path.join(root, branchName);

execSync(`git worktree remove ${fullPath}`);
console.log(`Worktree ${fullPath.replace(process.env.HOME, "~")} removed.`);

updateWorkspaceFile(root, (json) => ({
  ...json,
  folders: json.folders.filter((x) => x.name !== branchName),
}));
