#!/usr/bin/env node
const path = require("path");
const fs = require("fs");
const { execSync } = require("child_process");

const { find_git_root, updateWorkspaceFile } = require("./helpers");

const [remoteName, branchName] = process.argv[3]
  ? [process.argv[2], process.argv[3]]
  : ["origin", process.argv[2]];

const root = find_git_root(process.cwd());
const fullPath = path.join(root, branchName);

const currentBranch = execSync(`git branch --show-current`).toString().trim();

try {
  execSync(`git co -b ${branchName}`);
  execSync(`git push --set-upstream ${remoteName} ${branchName}`);
} catch (error) {
} finally {
  execSync(`git co ${currentBranch}`);
}

execSync(`git worktree add ${fullPath} ${branchName}`);

console.log(`Worktree ${fullPath.replace(process.env.HOME, "~")} created`);

updateWorkspaceFile(root, (json) => ({
  ...json,
  folders: [
    ...json.folders,
    { name: path.basename(branchName), path: branchName },
  ],
}));
