#!/usr/bin/env bash

# Used to go through each commit in a repo one by one
# for exploratory purposes.

set -x

git reset --hard HEAD
git clean -xfd
INDEX=$(cat /tmp/index)
INDEX=$(($INDEX + 1))
echo $INDEX > /tmp/index
TOTAL=$(git rev-list --branches main | wc -l)
NEXT=$(($TOTAL - $INDEX))
COMMIT=$(git rev-list --branches main | sed "${NEXT}q;d")
git co $COMMIT
git reset --soft HEAD~1
